// LTB Ingredient Database — canonical baseline costs
// Seeded once into app storage (INGREDIENTS_KEY); edit costs in-app after that.
// To re-baseline from scratch, clear the storage key and reload.

// Each ingredient: { id, name, unit (purchase unit), baseline ($ per purchase unit), category }
// Optional `fixed: true` marks ingredients that never drift (packaging, homegrown
// produce) — they still count toward raw cost but are excluded from margin drift.
export const INGREDIENT_SEED = [
  { id: 'garlic', name: 'Garlic', unit: 'head', baseline: 0.5, category: 'produce' },
  { id: 'ginger', name: 'Ginger', unit: 'lb', baseline: 4.0, category: 'produce' },
  { id: 'onion', name: 'Onion (yellow)', unit: 'each', baseline: 0.6, category: 'produce' },
  { id: 'red_onion', name: 'Red onion', unit: 'each', baseline: 1.2, category: 'produce' },
  { id: 'sweet_onion', name: 'Sweet onion', unit: 'lb', baseline: 1.4, category: 'produce' },
  { id: 'bulb_onion', name: 'Bulb/spring onion', unit: 'bunch', baseline: 2.0, category: 'produce' },
  { id: 'scallions', name: 'Scallions', unit: 'bunch', baseline: 0.6, category: 'produce' },
  { id: 'carrots', name: 'Carrots', unit: 'lb', baseline: 1.0, category: 'produce' },
  { id: 'celery', name: 'Celery', unit: 'head', baseline: 1.0, category: 'produce' },
  { id: 'green_bell_pepper', name: 'Green bell pepper', unit: 'each', baseline: 0.72, category: 'produce' },
  { id: 'poblano', name: 'Poblano', unit: 'lb', baseline: 1.8, category: 'produce' },
  { id: 'habanero', name: 'Habanero', unit: 'oz', baseline: 0.25, category: 'produce' },
  { id: 'ancho_chili', name: 'Ancho chili (dried)', unit: 'oz', baseline: 0.5, category: 'pantry' },
  { id: 'dried_peppers', name: 'Dried peppers', unit: '8oz', baseline: 3.0, category: 'pantry' },
  { id: 'chilis', name: 'Chilis (fresh mix)', unit: 'batch', baseline: 5.0, category: 'produce' },
  { id: 'cilantro', name: 'Cilantro', unit: 'bunch', baseline: 0.5, category: 'produce' },
  { id: 'basil', name: 'Thai basil', unit: 'bunch', baseline: 3.0, category: 'produce' },
  { id: 'mint', name: 'Mint', unit: 'bunch', baseline: 2.5, category: 'produce' },
  { id: 'thyme_fresh', name: 'Thyme (fresh)', unit: 'bunch', baseline: 1.0, category: 'produce' },
  { id: 'fennel_bulb', name: 'Fennel bulb', unit: 'each', baseline: 4.2, category: 'produce' },
  { id: 'asparagus', name: 'Asparagus', unit: 'lb', baseline: 4.0, category: 'produce' },
  { id: 'chinese_broccoli', name: 'Chinese broccoli', unit: 'lb', baseline: 4.0, category: 'produce' },
  { id: 'chinese_eggplant', name: 'Chinese eggplant', unit: 'lb', baseline: 2.19, category: 'produce' },
  { id: 'long_beans', name: 'Long beans', unit: 'lb', baseline: 4.99, category: 'produce' },
  { id: 'asian_greens', name: 'Asian greens', unit: 'lb', baseline: 2.0, category: 'produce' },
  { id: 'mushrooms', name: 'Mushrooms', unit: 'lb', baseline: 5.0, category: 'produce' },
  { id: 'baby_bella', name: 'Baby bella mushrooms', unit: '8oz', baseline: 3.0, category: 'produce' },
  { id: 'porcini', name: 'Dried porcini', unit: 'oz', baseline: 2.25, category: 'produce' },
  { id: 'oyster_mushroom', name: 'Oyster mushroom', unit: 'lb', baseline: 8.99, category: 'produce' },
  { id: 'king_oyster_mushroom', name: 'King oyster mushroom', unit: 'lb', baseline: 4.99, category: 'produce' },
  { id: 'shiitake', name: 'Shiitake mushroom', unit: 'lb', baseline: 7.99, category: 'produce' },
  { id: 'kabocha', name: 'Kabocha squash', unit: 'lb', baseline: 1.99, category: 'produce' },
  { id: 'petite_peas', name: 'Petite peas', unit: '8oz', baseline: 1.0, category: 'frozen' },
  { id: 'corn', name: 'Corn', unit: 'ear', baseline: 0.33, category: 'produce' },
  { id: 'red_potatoes', name: 'Red potatoes', unit: 'lb', baseline: 2.32, category: 'produce' },
  { id: 'baby_gold_potatoes', name: 'Baby gold potatoes', unit: 'lb', baseline: 2.0, category: 'produce' },
  { id: 'apple', name: 'Apple', unit: 'each', baseline: 1.5, category: 'produce' },
  { id: 'lemon', name: 'Lemon', unit: 'each', baseline: 0.5, category: 'produce' },
  { id: 'lime', name: 'Lime', unit: 'each', baseline: 0.25, category: 'produce' },
  { id: 'cantaloupe', name: 'Seasonal melon', unit: 'each', baseline: 3.0, category: 'produce' },
  { id: 'pineapple', name: 'Pineapple (per container)', unit: 'container', baseline: 2.5, category: 'produce' },
  { id: 'ground_beef', name: 'Ground beef', unit: 'lb', baseline: 7.0, category: 'protein' },
  { id: 'ground_pork', name: 'Ground pork', unit: 'lb', baseline: 5.0, category: 'protein' },
  { id: 'ground_chicken', name: 'Ground chicken', unit: 'lb', baseline: 5.0, category: 'protein' },
  { id: 'ground_lamb', name: 'Ground lamb', unit: 'lb', baseline: 12.99, category: 'protein' },
  { id: 'chicken_thighs', name: 'Chicken thighs', unit: 'lb', baseline: 5.0, category: 'protein' },
  { id: 'chicken_breast', name: 'Chicken breast', unit: 'lb', baseline: 5.0, category: 'protein' },
  { id: 'beef_chuck', name: 'Beef chuck roast', unit: 'lb', baseline: 9.02, category: 'protein' },
  { id: 'pork_butt', name: 'Pork butt roast (bone-in)', unit: 'lb', baseline: 2.75, category: 'protein' },
  { id: 'pork_shoulder', name: 'Pork shoulder (bone-in)', unit: 'lb', baseline: 2.59, category: 'protein' },
  { id: 'wagyu_london_broil', name: 'Wagyu london broil', unit: 'lb', baseline: 12.0, category: 'protein' },
  { id: 'pork_tenderloin', name: 'Pork tenderloin', unit: 'lb', baseline: 7.29, category: 'protein' }, // raw cost for recipe use (the bag item carries its own costPerLb)
  { id: 'shrimp', name: 'Shrimp', unit: 'lb', baseline: 14.0, category: 'protein' },
  { id: 'tofu', name: 'Tofu', unit: 'block', baseline: 2.5, category: 'protein' },
  { id: 'salt_pork', name: 'Salt pork', unit: 'oz', baseline: 0.17, category: 'protein' },
  { id: 'anchovies', name: 'Anchovies (fillet)', unit: 'fillet', baseline: 0.3, category: 'pantry' }, // Kevin's jar: $6.07 / ~20 fillets = $0.30/fillet. ALWAYS the same container — receipt scans convert jar price via packQty 20.
  { id: 'kimchi', name: 'Kimchi', unit: 'jar', baseline: 8.0, category: 'pantry' },
  { id: 'butter', name: 'Butter', unit: 'stick', baseline: 0.95, category: 'dairy' },
  { id: 'milk', name: 'Milk', unit: 'cup', baseline: 0.275, category: 'dairy' },
  { id: 'evaporated_milk', name: 'Evaporated milk', unit: 'cup', baseline: 1.53, category: 'dairy' },
  { id: 'heavy_cream', name: 'Heavy cream', unit: 'cup', baseline: 3.0, category: 'dairy' },
  { id: 'eggs', name: 'Eggs', unit: 'each', baseline: 0.25, category: 'dairy' },
  { id: 'parm', name: 'Parmesan (good)', unit: 'lb', baseline: 23.0, category: 'dairy' },
  { id: 'oaxaca', name: 'Oaxaca cheese', unit: 'lb', baseline: 8.12, category: 'dairy' },
  { id: 'colby_jack', name: 'Colby jack', unit: 'lb', baseline: 5.41, category: 'dairy' },
  { id: 'flour', name: 'Flour', unit: 'lb', baseline: 0.75, category: 'pantry' },
  { id: 'baking_powder', name: 'Baking powder', unit: 'tbs', baseline: 0.18, category: 'pantry' },
  { id: 'baking_soda', name: 'Baking soda', unit: 'tbs', baseline: 0.1, category: 'pantry' },
  { id: 'white_sugar', name: 'White sugar', unit: 'cup', baseline: 0.4, category: 'pantry' },
  { id: 'brown_sugar', name: 'Brown sugar', unit: 'cup', baseline: 0.57, category: 'pantry' },
  { id: 'dark_brown_sugar', name: 'Dark brown sugar', unit: 'cup', baseline: 0.57, category: 'pantry' },
  { id: 'molasses', name: 'Molasses', unit: 'tbs', baseline: 0.1, category: 'pantry' },
  { id: 'white_karo', name: 'White Karo syrup', unit: 'cup', baseline: 1.6, category: 'pantry' },
  { id: 'honey', name: 'Honey', unit: 'tbs', baseline: 0.2, category: 'pantry' },
  { id: 'cocoa', name: 'Cocoa powder', unit: 'tbs', baseline: 0.19, category: 'pantry' },
  { id: 'chocolate_100', name: '100% chocolate', unit: 'square', baseline: 0.5, category: 'pantry' },
  { id: 'guittard_low', name: 'Guittard chocolate (low %)', unit: 'g', baseline: 0.02749, category: 'pantry' },
  { id: 'guittard_high', name: 'Guittard chocolate (high %)', unit: 'g', baseline: 0.02749, category: 'pantry', priceLink: 'guittard_low' },
  { id: 'valrhona', name: 'Valrhona chocolate (premium)', unit: '290g', baseline: 19.0, category: 'pantry' },
  { id: 'peanut_butter', name: 'Peanut butter', unit: 'half-jar', baseline: 0.7, category: 'pantry' },
  { id: 'vanilla', name: 'Vanilla (imitation)', unit: 'tbs', baseline: 0.07, category: 'pantry' },
  { id: 'vanilla_extract', name: 'Vanilla extract (homemade)', unit: 'tbs', baseline: 1.5, category: 'pantry' },
  { id: 'rice', name: 'Rice', unit: 'batch', baseline: 1.0, category: 'pantry' },
  { id: 'pasta', name: 'Pasta (dry)', unit: 'lb', baseline: 2.0, category: 'pantry', passthrough: true }, // store-bought, sold at cost
  { id: 'egg_pappardelle', name: 'Egg pappardelle', unit: 'pack', baseline: 4.2, category: 'pantry', passthrough: true }, // store-bought, sold at cost
  { id: 'noodles', name: 'Noodles (fresh)', unit: 'batch', baseline: 8.0, category: 'pantry' },
  { id: 'tortillas', name: 'Tortillas', unit: '10ct', baseline: 2.0, category: 'pantry' },
  { id: 'dried_kidney_beans', name: 'Dried kidney beans', unit: 'lb', baseline: 1.22, category: 'pantry' },
  { id: 'dried_lima_beans', name: 'Dried lima beans', unit: 'oz', baseline: 0.13, category: 'pantry' },
  { id: 'black_beans', name: 'Black beans (dried)', unit: 'lb', baseline: 0.55, category: 'pantry' },
  { id: 'chickpeas', name: 'Chickpeas (dried)', unit: 'lb', baseline: 1.5, category: 'pantry' }, // estimate, not receipt-verified yet
  { id: 'tomato_can', name: 'Canned tomato (28oz)', unit: 'can', baseline: 3.54, category: 'pantry' },
  { id: 'peeled_tomatoes', name: 'Peeled tomatoes (14oz)', unit: 'can', baseline: 1.08, category: 'pantry' },
  { id: 'fresh_tomatoes', name: 'Fresh tomatoes', unit: 'lb', baseline: 4.0, category: 'produce' },
  { id: 'homegrown_tomatoes', name: 'Homegrown tomatoes', unit: '28oz can-equiv', baseline: 10.0, category: 'produce', fixed: true },
  { id: 'tomato_paste', name: 'Tomato paste', unit: 'can', baseline: 1.0, category: 'pantry' },
  { id: 'canola_oil', name: 'Canola oil', unit: 'cup', baseline: 0.74, category: 'pantry' },
  { id: 'vegetable_oil', name: 'Vegetable oil', unit: 'cup', baseline: 0.58, category: 'pantry' },
  { id: 'olive_oil', name: 'Good olive oil (Graza Drizzle)', unit: 'oz', baseline: 1.27, category: 'pantry' }, // finishing oil — 500 ml bottle; the 'Good olive oil' recipe line
  { id: 'olive_oil_cooking', name: 'Cooking olive oil (Graza Sizzle)', unit: 'oz', baseline: 0.79, category: 'pantry' }, // everyday cooking oil — 750 ml bottle; distinct oil, do NOT conflate (Kevin, Jul 5)
  { id: 'oil_generic', name: 'Cooking oil', unit: 'cup', baseline: 0.7, category: 'pantry' },
  { id: 'toasted_sesame', name: 'Toasted sesame oil', unit: 'tbs', baseline: 0.12, category: 'pantry' },
  { id: 'chili_oil', name: 'Chili oil (house)', unit: 'cup', baseline: 2.3, category: 'pantry' },
  { id: 'soy', name: 'Soy sauce', unit: 'tbs', baseline: 0.05, category: 'pantry' },
  { id: 'dark_soy', name: 'Dark soy', unit: 'tbs', baseline: 0.1, category: 'pantry' },
  { id: 'light_soy', name: 'Light soy', unit: 'tbs', baseline: 0.05, category: 'pantry' },
  { id: 'oyster_sauce', name: 'Oyster sauce', unit: 'tbs', baseline: 0.22, category: 'pantry' },
  { id: 'fish_sauce', name: 'Fish sauce', unit: 'tbs', baseline: 0.2, category: 'pantry' },
  { id: 'doubanjiang', name: 'Doubanjiang', unit: 'tbs', baseline: 1.0, category: 'pantry' },
  { id: 'fermented_black_beans', name: 'Fermented black beans', unit: 'tbs', baseline: 0.125, category: 'pantry' },
  { id: 'worcestershire', name: 'Worcestershire', unit: 'tbs', baseline: 0.28, category: 'pantry' },
  { id: 'franks', name: 'Frank\'s hot sauce', unit: 'batch-use', baseline: 0.5, category: 'pantry' },
  { id: 'marmite', name: 'Marmite', unit: 'batch-use', baseline: 2.0, category: 'pantry' },
  { id: 'chinkiang', name: 'Chinkiang vinegar', unit: 'tbs', baseline: 0.083, category: 'pantry' },
  { id: 'vinegar', name: 'Vinegar (generic)', unit: 'batch-use', baseline: 0.5, category: 'pantry' },
  { id: 'red_wine', name: 'Red wine', unit: 'cup', baseline: 2.5, category: 'pantry' },
  { id: 'white_wine', name: 'White wine', unit: 'cup', baseline: 2.5, category: 'pantry' },
  { id: 'shaoxing', name: 'Shaoxing wine', unit: 'cup', baseline: 3.0, category: 'pantry' },
  { id: 'sherry', name: 'Sherry', unit: 'cup', baseline: 8.0, category: 'pantry' },
  { id: 'marsala', name: 'Marsala wine (dry or sweet)', unit: 'cup', baseline: 4.1, category: 'pantry' }, // $13/750ml ÷ 3.17 cups; dry & sweet priced the same (Kevin)
  { id: 'shallot', name: 'Shallot', unit: 'lb', baseline: 3.98, category: 'produce' },
  { id: 'whole_grain_mustard', name: 'Whole grain mustard', unit: 'oz', baseline: 0.17, category: 'pantry' },
  { id: 'egg_taglierini', name: 'Egg taglierini', unit: 'pack', baseline: 3.98, category: 'pantry' , passthrough: true }, // store-bought, sold at cost
  { id: 'polenta', name: 'Polenta (dry cornmeal)', unit: 'lb', baseline: 5.99, category: 'pantry' }, // measured: 0.795 lb = 1.75 cups dry
  { id: 'tarragon', name: 'Tarragon (fresh)', unit: 'bunch', baseline: 2.5, category: 'produce' },
  { id: 'bourbon', name: 'Bourbon', unit: 'cup', baseline: 6.4, category: 'pantry' },
  { id: 'espresso', name: 'Espresso', unit: 'shot', baseline: 1.5, category: 'pantry' },
  { id: 'salt', name: 'Salt', unit: 'batch-use', baseline: 0.05, category: 'spice' },
  { id: 'kosher_salt', name: 'Kosher salt', unit: 'tbs', baseline: 0.02, category: 'spice' },
  { id: 'black_pepper', name: 'Black pepper', unit: 'batch-use', baseline: 0.1, category: 'spice' },
  { id: 'bay_leaf', name: 'Bay leaf', unit: 'leaf', baseline: 0.05, category: 'spice' },
  { id: 'nutmeg', name: 'Nutmeg', unit: 'batch-use', baseline: 0.1, category: 'spice' },
  { id: 'fennel_seeds', name: 'Fennel seeds', unit: 'tsp', baseline: 0.1, category: 'spice' },
  { id: 'saffron', name: 'Saffron', unit: 'pinch', baseline: 1.17, category: 'spice' }, // HEB 0.018oz bag $4.68 / 4 Small servings per bag (Kevin's ratio)
  { id: 'curry_powder', name: 'Curry powder', unit: 'batch-use', baseline: 1.0, category: 'spice' },
  { id: 'curry_spices', name: 'Curry spice blend', unit: 'batch-use', baseline: 1.0, category: 'spice' },
  { id: 'five_spice', name: '5-spice powder', unit: 'tsp', baseline: 0.125, category: 'spice' },
  { id: 'sichuan_pepper', name: 'Sichuan peppercorns', unit: 'tsp', baseline: 0.0625, category: 'spice' },
  { id: 'star_anise', name: 'Star anise', unit: 'each', baseline: 0.0625, category: 'spice' },
  { id: 'chili_flakes', name: 'Chili flakes', unit: 'tbs', baseline: 0.166, category: 'spice' },
  { id: 'spices_generic', name: 'Spice blend (generic)', unit: 'batch-use', baseline: 1.0, category: 'spice' },
  { id: 'cornstarch', name: 'Cornstarch', unit: 'batch-use', baseline: 0.1, category: 'pantry' },
  { id: 'wrap', name: 'Packaging (wrap/jar)', unit: 'each', baseline: 1.0, category: 'pantry', fixed: true },
  { id: 'sv_bag', name: 'Sous vide bag + butter + herbs', unit: 'each', baseline: 1.5, category: 'pantry', fixed: true }, // composed sous vide dishes: bag + seasoning cost tracked separately from packaging
  { id: 'sodium_citrate', name: 'Sodium citrate', unit: 'g', baseline: 0.025, category: 'pantry' },
  { id: 'herb_generic', name: 'Herb (thyme/lavender)', unit: 'batch', baseline: 1.0, category: 'produce' },
  { id: 'chicken_stock', name: 'Chicken stock', unit: 'cup', baseline: 0.745, category: 'pantry' },
  { id: 'beef_stock', name: 'Beef stock', unit: 'cup', baseline: 0.75, category: 'pantry' },
  { id: 'chicken_basics_stock', name: 'Kitchen Basics stock', unit: 'carton', baseline: 2.98, category: 'pantry' },
  { id: 'orange_juice', name: 'Orange juice', unit: 'batch-use', baseline: 2.0, category: 'pantry' },
  { id: 'lime_juice', name: 'Lime juice', unit: 'g', baseline: 0.0125, category: 'produce' },
];

// Conversion anchors for mapping recipe quantities to purchase units (phase 2 dish linkage)
export const CONVERSIONS = {
  garlic:  { perPurchase: 20, recipeUnit: 'clove' },   // 20 big cloves per head
  ginger:  { gramsPerLb: 453.6, gramsPerKnob: 30 },    // knob = 30g peeled; lb purchase
  onion:   { lbPerEach: 0.6 },                          // 1 onion ~ 0.6 lb
};

export const CATEGORY_ORDER = ['produce','protein','dairy','pantry','spice','frozen'];
export const CATEGORY_LABELS_ING = {
  produce: 'Produce', protein: 'Proteins', dairy: 'Dairy & Eggs',
  pantry: 'Pantry & Dry', spice: 'Spices & Aromatics', frozen: 'Frozen',
};
