// Color palette and the giant  object used by every component.

export const TEAL_DARK = '#1a3a3a';
export const TEAL_MID = '#2E6B6B';
export const TEAL_LIGHT = '#5DCAA5';
export const GOLD = '#C49A3C';
export const CREAM = '#F5F0E8';
export const DARK = '#1a1a1a';
export const CARD = '#222826';

export const styles = {
  page: {
    minHeight: '100vh',
    background: DARK,
    color: CREAM,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    paddingBottom: '40px',
  },
  loadingText: {
    padding: '40px 20px',
    textAlign: 'center',
    color: '#9aa5a0',
  },
  header: {
    background: TEAL_DARK,
    borderBottom: `2px solid ${GOLD}`,
    padding: '16px 16px 0',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  headerTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
  },
  headerCenter: {
    flex: 1,
  },
  headerActions: {
    display: 'flex',
    gap: '6px',
    alignItems: 'center',
    flexShrink: 0,
  },
  headerActionBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '34px',
    height: '34px',
    background: 'transparent',
    border: '1px solid #37403c',
    borderRadius: '8px',
    color: '#9aa5a0',
    cursor: 'pointer',
    flexShrink: 0,
  },
  exportMsg: {
    fontSize: '12px',
    color: TEAL_LIGHT,
    background: '#0f2e2a',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '6px',
    padding: '7px 12px',
    margin: '0 16px 8px',
    textAlign: 'center',
  },
  importModalCard: {
    width: '100%',
    maxWidth: '420px',
    background: CARD,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '14px',
    padding: '18px',
    boxSizing: 'border-box',
  },
  importModalHint: {
    fontSize: '13px',
    color: '#9aa5a0',
    marginBottom: '10px',
    lineHeight: 1.4,
  },
  logoMark: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    background: '#085041',
    border: `1.5px solid ${TEAL_LIGHT}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: 700,
    color: TEAL_LIGHT,
    flexShrink: 0,
  },
  title: {
    fontSize: '17px',
    fontWeight: 700,
    color: '#fff',
  },
  subtitle: {
    fontSize: '12px',
    color: TEAL_LIGHT,
  },
  tabs: {
    display: 'flex',
    gap: '2px',
  },
  tab: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    color: '#9aa5a0',
    fontSize: '13px',
    fontWeight: 600,
    padding: '10px 4px',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '5px',
  },
  tabActive: {
    color: TEAL_LIGHT,
    borderBottom: `2px solid ${TEAL_LIGHT}`,
  },
  tabBadge: {
    background: TEAL_LIGHT,
    color: '#04342C',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 700,
    padding: '1px 7px',
  },
  errorBanner: {
    display: 'block',
    width: '100%',
    background: '#501313',
    color: '#F7C1C1',
    padding: '10px 16px',
    fontSize: '13px',
    textAlign: 'center',
    border: 'none',
    borderBottom: '1px solid #6b1a1a',
    cursor: 'pointer',
  },
  errorRetry: {
    display: 'block',
    fontSize: '11px',
    color: '#F7C1C1',
    opacity: 0.7,
    marginTop: '3px',
    textDecoration: 'underline',
  },
  main: {
    padding: '16px',
    maxWidth: '560px',
    margin: '0 auto',
  },
  statsBar: {
    display: 'flex',
    gap: '8px',
    marginBottom: '14px',
  },
  statTile: {
    flex: 1,
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '10px',
    padding: '10px 8px',
    textAlign: 'center',
  },
  statValue: {
    fontSize: '16px',
    fontWeight: 700,
    color: TEAL_LIGHT,
  },
  statLabel: {
    fontSize: '11px',
    color: '#9aa5a0',
    marginTop: '2px',
  },
  topActions: {
    display: 'flex',
    gap: '8px',
    marginBottom: '16px',
    flexWrap: 'wrap',
  },
  newOrderBtn: {
    flex: 1.4,
    background: '#085041',
    color: TEAL_LIGHT,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '10px',
    padding: '14px',
    fontSize: '15px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    cursor: 'pointer',
  },
  pasteBtn: {
    flex: 1,
    background: 'transparent',
    color: '#B5A2E8',
    border: '1px solid #7F77DD',
    borderRadius: '10px',
    padding: '14px',
    fontSize: '14px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    cursor: 'pointer',
  },
  // Disabled-button look for the dormant AI text features (GitHub build).
  disabledBtn: {
    opacity: 0.4,
    cursor: 'not-allowed',
    filter: 'grayscale(100%)',
  },
  // ── Pending form orders styles ────────────────────────────────────────────
  pendingSection: {
    marginBottom: '12px',
    borderRadius: '12px',
    border: '2px solid #c9a84c',
    overflow: 'hidden',
  },
  pendingSectionHeader: {
    background: '#2a3a2a',
    padding: '10px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  pendingSectionTitle: {
    color: '#c9a84c',
    fontWeight: 700,
    fontSize: '13px',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  pendingBadge: {
    background: '#c9a84c',
    color: '#1a3a3a',
    borderRadius: '10px',
    padding: '1px 7px',
    fontSize: '12px',
    fontWeight: 800,
  },
  pendingRow: {
    width: '100%',
    background: '#1e2e1e',
    border: 'none',
    borderTop: '1px solid #2d4a2d',
    padding: '12px 14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    color: '#d4c9a8',
    textAlign: 'left',
  },
  pendingRowName: {
    flex: 1,
    fontWeight: 600,
    fontSize: '14px',
  },
  pendingRowCount: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  pendingCard: {
    background: '#1e2e1e',
    borderTop: '1px solid #2d4a2d',
    padding: '14px',
  },
  pendingCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: '10px',
  },
  pendingContactRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    marginTop: '5px',
  },
  pendingContact: {
    fontSize: '12px',
    color: '#9aa5a0',
    lineHeight: 1.4,
  },
  orderContactBlock: {
    background: '#1a1a1a',
    border: '1px solid #2d3a36',
    borderRadius: '8px',
    padding: '9px 12px',
    marginBottom: '10px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    cursor: 'pointer',
  },
  orderContactRow: {
    fontSize: '13px',
    color: '#9aa5a0',
    lineHeight: 1.4,
  },
  contactBtnRow: {
    display: 'flex',
    gap: '6px',
    marginTop: '6px',
  },
  contactActionBtn: {
    fontSize: '11px',
    fontWeight: 600,
    color: TEAL_LIGHT,
    background: 'rgba(63,184,160,0.1)',
    border: '1px solid rgba(63,184,160,0.3)',
    borderRadius: '6px',
    padding: '4px 10px',
    cursor: 'pointer',
  },
  weekNotesBlock: {
    background: '#1f2624',
    border: '1px solid #2d6a6a',
    borderRadius: '12px',
    padding: '14px',
    marginBottom: '14px',
  },
  weekNotesTitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: GOLD,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '8px',
  },
  weekNotesBody: {
    fontSize: '13px',
    color: '#cfd6d2',
    lineHeight: 1.5,
    cursor: 'pointer',
  },
  pendingCardName: {
    fontWeight: 700,
    fontSize: '15px',
    color: '#e8dfc0',
  },
  pendingCardTime: {
    fontSize: '11px',
    color: '#9aa5a0',
  },
  pendingItemList: {
    marginBottom: '12px',
  },
  pendingItem: {
    padding: '4px 0',
    borderBottom: '1px solid #2d4a2d',
    fontSize: '13px',
  },
  pendingItemName: {
    color: '#d4c9a8',
    fontWeight: 600,
  },
  pendingItemVariant: {
    color: '#9aa5a0',
  },
  pendingItemPrice: {
    color: '#c9a84c',
    float: 'right',
  },
  pendingNotes: {
    marginTop: '8px',
    fontSize: '12px',
    color: '#9aa5a0',
    fontStyle: 'italic',
  },
  pendingActions: {
    display: 'flex',
    gap: '8px',
  },
  pendingAcceptBtn: {
    flex: 1,
    background: '#1D9E75',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  pendingRejectBtn: {
    flex: 1,
    background: '#8B2020',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  pendingBackBtn: {
    background: 'transparent',
    color: '#9aa5a0',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 14px',
    fontSize: '13px',
    cursor: 'pointer',
  },
  pendingNotesSection: {
    marginBottom: '10px',
  },
  parsedNotesCard: {
    background: '#1a2e1a',
    border: '1px solid #3a6a3a',
    borderRadius: '8px',
    padding: '10px',
    marginTop: '6px',
  },
  parsedNotesTitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#7abf7a',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '6px',
  },
  parsedNotesSummary: {
    fontSize: '13px',
    color: '#e8dfc0',
    fontWeight: 600,
    marginBottom: '6px',
  },
  parsedNotesItem: {
    fontSize: '12px',
    color: '#9aa5a0',
    marginBottom: '3px',
  },
  parsedNotesKey: {
    color: '#c9a84c',
    fontWeight: 600,
    textTransform: 'capitalize',
  },
  parseNotesBtn: {
    marginTop: '6px',
    background: '#1a2e1a',
    color: '#7abf7a',
    border: '1px solid #3a6a3a',
    borderRadius: '8px',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    width: '100%',
  },
  // ── Regulars: list, form, profile ──────────────────────────────────────────
  addRegularBtn: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    background: '#c9a84c',
    color: '#1a3a3a',
    border: 'none',
    borderRadius: '10px',
    padding: '13px',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
    marginBottom: '12px',
  },
  regularsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  regularRow: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#232a28',
    border: '1px solid #2d3a36',
    borderRadius: '10px',
    padding: '14px',
    cursor: 'pointer',
    color: '#e8e2d4',
    textAlign: 'left',
  },
  regularRowLeft: { flex: 1 },
  regularRowName: { fontSize: '15px', fontWeight: 700, color: '#f2f2f0' },
  regularRowMeta: { fontSize: '12px', color: '#9aa5a0', marginTop: '2px' },
  regularStar: { color: '#c9a84c' },
  regularFormCard: {
    background: '#232a28',
    border: '1px solid #2d3a36',
    borderRadius: '12px',
    padding: '14px',
  },
  regularFormHint: {
    fontSize: '11px',
    color: '#9aa5a0',
    fontStyle: 'italic',
    marginTop: '4px',
    marginBottom: '4px',
  },
  nameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '8px',
  },
  nameRemoveBtn: {
    width: '34px',
    height: '34px',
    flexShrink: 0,
    borderRadius: '8px',
    border: '1px solid #5a2a3a',
    background: 'transparent',
    color: '#C0517A',
    fontSize: '20px',
    fontWeight: 700,
    cursor: 'pointer',
    lineHeight: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addNameBtn: {
    background: 'transparent',
    color: '#7abf7a',
    border: '1px dashed #3a6a3a',
    borderRadius: '8px',
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    marginBottom: '4px',
  },
  regularFormActions: {
    display: 'flex',
    gap: '8px',
    marginTop: '14px',
  },
  profileBackBtn: {
    background: 'transparent',
    color: '#7abf7a',
    border: 'none',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
    padding: '4px 0',
    marginBottom: '8px',
  },
  profileHeader: {
    background: 'linear-gradient(135deg, #1a3a3a, #232a28)',
    border: '1px solid #2d6a6a',
    borderRadius: '12px',
    padding: '16px',
    marginBottom: '12px',
  },
  profileName: {
    fontSize: '20px',
    fontWeight: 800,
    color: '#f2f2f0',
    marginBottom: '12px',
  },
  profileSummaryGrid: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '8px',
  },
  profileStat: {
    flex: 1,
    textAlign: 'center',
    background: '#1a1a1a55',
    borderRadius: '8px',
    padding: '8px 4px',
  },
  profileStatNum: { fontSize: '15px', fontWeight: 700, color: '#c9a84c' },
  profileStatLabel: { fontSize: '10px', color: '#9aa5a0', textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: '2px' },
  profileDiscountBadge: {
    marginTop: '10px',
    display: 'inline-block',
    background: '#c9a84c22',
    color: '#c9a84c',
    border: '1px solid #c9a84c55',
    borderRadius: '6px',
    padding: '4px 10px',
    fontSize: '12px',
    fontWeight: 600,
  },
  profileSection: {
    background: '#232a28',
    border: '1px solid #2d3a36',
    borderRadius: '12px',
    padding: '14px',
    marginBottom: '10px',
  },
  profileSectionTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#c9a84c',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '8px',
  },
  profileField: { fontSize: '13px', color: '#d8d2c4', marginBottom: '4px', lineHeight: 1.4 },
  profileFieldKey: { color: '#9aa5a0', fontWeight: 600 },
  profileFieldEmpty: { fontSize: '13px', color: '#6a726c', fontStyle: 'italic' },
  profileEditBtn: {
    marginTop: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    background: 'transparent',
    color: '#7abf7a',
    border: '1px solid #37403c',
    borderRadius: '7px',
    padding: '6px 10px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  profileNotes: {
    fontSize: '13px',
    color: '#d8d2c4',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap',
  },
  profileNoteLine: { marginBottom: '3px' },
  profileInsightLine: {
    marginBottom: '4px',
    color: '#7abf7a',
    fontSize: '12px',
    fontStyle: 'italic',
    background: '#1a2e1a',
    borderRadius: '5px',
    padding: '4px 7px',
  },
  profileHistoryList: { display: 'flex', flexDirection: 'column', gap: '6px' },
  profileHistoryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottom: '1px solid #2d3a36',
    paddingBottom: '6px',
  },
  profileHistoryLeft: { flex: 1, paddingRight: '8px' },
  profileHistoryDate: { fontSize: '12px', fontWeight: 600, color: '#d8d2c4' },
  profileHistoryItems: { fontSize: '11px', color: '#9aa5a0', marginTop: '2px', lineHeight: 1.3 },
  profileHistoryRight: { display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '2px' },
  profileHistoryTotal: { fontSize: '13px', fontWeight: 700, color: '#c9a84c' },
  profileUnlinkBtn: {
    background: 'transparent',
    color: '#8a928c',
    border: 'none',
    fontSize: '11px',
    cursor: 'pointer',
    textDecoration: 'underline',
    padding: 0,
  },
  profileLinkBtn: {
    marginTop: '10px',
    width: '100%',
    background: '#1f2937',
    color: '#93b4d4',
    border: '1px solid #3d5a7a',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  linkBrowser: { marginTop: '10px' },
  linkBrowserList: { marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '5px', maxHeight: '300px', overflowY: 'auto' },
  linkBrowserRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: '#1a1a1a',
    border: '1px solid #2d3a36',
    borderRadius: '7px',
    padding: '9px 11px',
    cursor: 'pointer',
    textAlign: 'left',
  },
  linkBrowserRowLeft: { display: 'flex', flexDirection: 'column', flex: 1 },
  linkBrowserName: { fontSize: '13px', fontWeight: 600, color: '#e8e2d4' },
  linkBrowserItems: { fontSize: '10px', color: '#8a928c', marginTop: '1px' },
  linkBrowserMeta: { fontSize: '10px', color: '#9aa5a0', textAlign: 'right' },
  profileDeleteBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    background: 'transparent',
    color: '#C0517A',
    border: '1px solid #5a2a3a',
    borderRadius: '7px',
    padding: '8px 12px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  profileDeleteConfirm: {
    fontSize: '13px',
    color: '#d8d2c4',
    lineHeight: 1.4,
  },
  confirmDeleteRed: {
    flex: 1,
    background: '#8B2020',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  orderRegularStar: { color: '#c9a84c', fontSize: '15px' },
  // ── Regular discount toggle on order card ──────────────────────────────────
  regularDiscountToggle: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#1a2e1a',
    border: '1px solid #3a6a3a',
    borderRadius: '9px',
    padding: '10px 12px',
    cursor: 'pointer',
    marginBottom: '10px',
  },
  regularDiscountLabel: { fontSize: '13px', fontWeight: 600, color: '#c9a84c' },
  toggleSwitch: {
    width: '40px',
    height: '22px',
    borderRadius: '11px',
    background: '#37403c',
    position: 'relative',
    transition: 'background 0.15s',
    flexShrink: 0,
  },
  toggleSwitchOn: { background: '#1D9E75' },
  toggleKnob: {
    position: 'absolute',
    top: '2px',
    left: '2px',
    width: '18px',
    height: '18px',
    borderRadius: '9px',
    background: '#fff',
    transition: 'left 0.15s',
  },
  toggleKnobOn: { left: '20px' },
  // ── Link regular prompt modal ──────────────────────────────────────────────
  linkPromptCard: {
    background: '#232a28',
    border: '1px solid #2d6a6a',
    borderRadius: '14px',
    padding: '20px',
    maxWidth: '340px',
    width: '90%',
    margin: 'auto',
  },
  linkPromptTitle: { fontSize: '16px', fontWeight: 700, color: '#c9a84c', marginBottom: '8px' },
  linkPromptBody: { fontSize: '13px', color: '#d8d2c4', lineHeight: 1.4, marginBottom: '14px' },
  linkPromptList: { display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '12px' },
  linkPromptCandidate: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    background: '#1a3a3a',
    border: '1px solid #2d6a6a',
    borderRadius: '9px',
    padding: '11px 13px',
    cursor: 'pointer',
  },
  linkPromptCandidateName: { fontSize: '14px', fontWeight: 700, color: '#f2f2f0' },
  linkPromptCandidateMeta: { fontSize: '11px', color: '#c9a84c', marginTop: '2px' },
  linkPromptSkip: {
    width: '100%',
    background: 'transparent',
    color: '#9aa5a0',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    cursor: 'pointer',
  },
  // ── Inventory tracker (Shop tab) ───────────────────────────────────────────
  publishOk: {
    marginTop: '8px',
    fontSize: '12px',
    color: '#7abf7a',
    background: '#1a2e1a',
    border: '1px solid #3a6a3a',
    borderRadius: '8px',
    padding: '8px 10px',
    lineHeight: 1.4,
  },
  publishErr: {
    marginTop: '8px',
    fontSize: '12px',
    color: '#e0828a',
    background: '#3a1a1f',
    border: '1px solid #5a2a3a',
    borderRadius: '8px',
    padding: '8px 10px',
    lineHeight: 1.4,
  },
  collapsibleHeader: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    textAlign: 'left',
  },
  collapseChevron: {
    fontSize: '11px',
    color: '#9aa5a0',
    flexShrink: 0,
    marginLeft: '8px',
  },
  inventorySection: {
    background: '#232a28',
    border: '1px solid #2d6a6a',
    borderRadius: '12px',
    padding: '14px',
    marginBottom: '14px',
  },
  inventoryTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#fff',
    marginBottom: '4px',
  },
  inventoryHint: {
    fontSize: '11px',
    color: '#9aa5a0',
    fontStyle: 'italic',
    marginBottom: '12px',
    lineHeight: 1.4,
  },
  inventoryGroup: { marginBottom: '14px' },
  inventoryGroupLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#8a928c',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '6px',
  },
  inventoryRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 0',
    borderBottom: '1px solid #2d3a36',
  },
  inventoryName: { fontSize: '13px', color: '#e8e2d4', flex: 1 },
  inventoryControls: { display: 'flex', alignItems: 'center', gap: '10px' },
  inventoryBtn: {
    width: '30px',
    height: '30px',
    borderRadius: '8px',
    border: '1px solid #37403c',
    background: '#1a1a1a',
    color: '#e8e2d4',
    fontSize: '18px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  },
  inventoryCount: {
    minWidth: '34px',
    textAlign: 'center',
    fontSize: '16px',
    fontWeight: 700,
    color: '#f2f2f0',
  },
  inventoryCountYellow: { color: '#EF9F27' },
  inventoryCountRed: { color: '#E8799A' },
  // Strikethrough applied to the button label text only (keeps the icon intact).
  struckText: {
    textDecoration: 'line-through',
    textDecorationThickness: '2px',
  },
  pasteHint: {
    fontSize: '12px',
    color: '#9aa5a0',
    lineHeight: 1.5,
    marginBottom: '8px',
  },
  attachRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '8px',
    flexWrap: 'wrap',
  },
  attachBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#B5A2E8',
    background: 'transparent',
    border: '1px solid #7F77DD',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
  },
  attachChip: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '4px 4px 4px 10px',
  },
  attachName: {
    fontSize: '12px',
    color: CREAM,
    maxWidth: '140px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  shopBulkRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginTop: '12px',
    flexWrap: 'wrap',
  },
  parseError: {
    fontSize: '12px',
    color: '#F7C1C1',
    background: '#501313',
    borderRadius: '6px',
    padding: '8px 10px',
    marginTop: '8px',
  },
  emptyState: {
    textAlign: 'center',
    padding: '48px 20px',
    color: '#9aa5a0',
  },
  emptyTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: CREAM,
    marginBottom: '6px',
  },
  emptyBody: {
    fontSize: '13px',
    lineHeight: 1.5,
  },
  orderList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  orderCard: {
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '10px',
    overflow: 'hidden',
  },
  orderCardHeader: {
    width: '100%',
    padding: '14px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'pointer',
    color: CREAM,
    textAlign: 'left',
  },
  orderCardLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    minWidth: 0,
  },
  orderCustomer: {
    fontSize: '15px',
    fontWeight: 600,
  },
  orderMeta: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  orderCardRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  paidPill: {
    fontSize: '11px',
    fontWeight: 700,
    padding: '4px 10px',
    borderRadius: '12px',
    cursor: 'pointer',
    border: 'none',
  },
  statusPill: {
    fontSize: '11px',
    fontWeight: 700,
    padding: '4px 10px',
    borderRadius: '12px',
    cursor: 'pointer',
    border: 'none',
  },
  orderCardBody: {
    padding: '0 14px 14px',
    borderTop: '1px solid #37403c',
  },
  orderItemsList: {
    padding: '12px 0 4px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  orderItemLine: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: CREAM,
    gap: '10px',
  },
  orderItemVariant: {
    color: '#9aa5a0',
    fontSize: '12px',
  },
  loopSummary: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    fontSize: '12px',
    color: TEAL_LIGHT,
    padding: '8px 0',
    borderTop: '1px dashed #37403c',
    marginTop: '4px',
  },
  notesBlock: {
    borderTop: '1px dashed #37403c',
    marginTop: '4px',
    paddingTop: '8px',
  },
  orderNotes: {
    fontSize: '12px',
    color: '#cccccc',
    fontStyle: 'italic',
    cursor: 'pointer',
    lineHeight: 1.5,
  },
  notesEditHint: {
    color: '#7a8480',
    fontSize: '11px',
  },
  addNoteBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#9aa5a0',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '2px 0',
  },
  notesEditActions: {
    display: 'flex',
    gap: '8px',
    marginTop: '6px',
  },
  orderCardFooter: {
    marginTop: '10px',
  },
  statusRow: {
    display: 'flex',
    gap: '6px',
    flexWrap: 'wrap',
    marginBottom: '10px',
  },
  statusOption: {
    flex: '1 1 auto',
    fontSize: '12px',
    fontWeight: 600,
    padding: '7px 10px',
    borderRadius: '8px',
    border: '1px solid #37403c',
    background: 'transparent',
    color: '#9aa5a0',
    cursor: 'pointer',
  },
  actionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    flexWrap: 'wrap',
  },
  actionBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: TEAL_LIGHT,
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '4px 0',
  },
  confirmRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
  },
  confirmText: {
    color: '#cccccc',
    fontSize: '12px',
  },
  confirmYes: {
    background: '#993556',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    padding: '5px 10px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  confirmYesGreen: {
    background: '#1D9E75',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    padding: '5px 10px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  confirmNo: {
    background: 'transparent',
    color: '#9aa5a0',
    border: '1px solid #37403c',
    borderRadius: '6px',
    padding: '5px 10px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  deliveredSection: {
    marginTop: '20px',
  },
  deliveredSummary: {
    fontSize: '13px',
    fontWeight: 600,
    color: '#9aa5a0',
    cursor: 'pointer',
    padding: '8px 0',
  },
  clearDeliveredBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#9aa5a0',
    background: 'transparent',
    border: '1px dashed #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    cursor: 'pointer',
    marginTop: '10px',
    width: '100%',
    justifyContent: 'center',
  },
  clearConfirmRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    marginTop: '10px',
    flexWrap: 'wrap',
  },

  // Form
  formCard: {
    background: CARD,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '10px',
    padding: '16px',
    marginBottom: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  formHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  formTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: '#fff',
  },
  iconBtn: {
    background: 'transparent',
    border: 'none',
    color: '#9aa5a0',
    cursor: 'pointer',
    padding: '4px',
  },
  label: {
    fontSize: '12px',
    fontWeight: 600,
    color: TEAL_LIGHT,
    marginTop: '10px',
    marginBottom: '4px',
  },
  input: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
    color: CREAM,
    outline: 'none',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '6px',
  },
  chip: {
    fontSize: '12px',
    fontWeight: 600,
    color: TEAL_LIGHT,
    background: '#0f2e2a',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '14px',
    padding: '5px 12px',
    cursor: 'pointer',
  },
  textarea: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
    color: CREAM,
    outline: 'none',
    minHeight: '60px',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  selectedSummary: {
    fontSize: '12px',
    color: TEAL_LIGHT,
    fontWeight: 600,
    marginBottom: '4px',
  },
  qtyControl: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  qtyBtn: {
    width: '26px',
    height: '26px',
    borderRadius: '6px',
    border: '1px solid #37403c',
    background: 'transparent',
    color: TEAL_LIGHT,
    fontSize: '16px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyValue: {
    fontSize: '14px',
    fontWeight: 600,
    minWidth: '16px',
    textAlign: 'center',
  },
  categoryGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '6px',
  },
  categoryBtn: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#cccccc',
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '8px 10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  categoryBtnActive: {
    color: TEAL_LIGHT,
    borderColor: TEAL_LIGHT,
    background: '#0f2e2a',
  },
  catCount: {
    background: GOLD,
    color: '#1a1a1a',
    borderRadius: '8px',
    fontSize: '10px',
    fontWeight: 700,
    padding: '1px 6px',
  },
  picker: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px',
    marginTop: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  pickerGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  pickerGroupName: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#fff',
  },
  pickerVariants: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  variantBtn: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: 'transparent',
    border: '1px solid #37403c',
    borderRadius: '6px',
    padding: '8px 10px',
    fontSize: '12px',
    color: CREAM,
    cursor: 'pointer',
    textAlign: 'left',
    minHeight: '38px',
  },
  variantBtnSelected: {
    borderColor: TEAL_LIGHT,
    background: '#0f2e2a',
  },
  variantLabel: {
    color: CREAM,
    flex: 1,
    paddingRight: '8px',
  },
  variantPrice: {
    color: GOLD,
    fontWeight: 700,
  },
  reviewList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginTop: '10px',
    paddingTop: '10px',
    borderTop: '1px dashed #37403c',
  },
  reviewRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
  },
  reviewText: {
    fontSize: '13px',
    color: CREAM,
    flex: 1,
  },
  loopRow: {
    display: 'flex',
    gap: '12px',
    marginTop: '4px',
  },
  loopField: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  loopHint: {
    fontSize: '11px',
    color: '#9aa5a0',
    marginTop: '4px',
  },
  discountRow: {
    display: 'flex',
    gap: '6px',
    alignItems: 'stretch',
  },
  discountTypeBtn: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#9aa5a0',
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '8px 14px',
    cursor: 'pointer',
  },
  discountTypeBtnActive: {
    color: '#E8799A',
    borderColor: '#E8799A',
    background: '#2e1a22',
  },
  discountLine: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: '#E8799A',
    fontWeight: 600,
    marginTop: '12px',
  },
  totalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: '14px',
    fontWeight: 600,
    color: CREAM,
    marginTop: '8px',
    paddingTop: '10px',
    borderTop: `1px solid ${TEAL_MID}`,
  },
  waiveSurchargeRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '8px 0 2px',
    marginTop: '4px',
  },
  waiveSurchargeLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    color: '#9aa5a0',
  },
  waiveCheckbox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '18px',
    height: '18px',
    borderRadius: '4px',
    border: '1px solid #4a5450',
    background: '#1a1a1a',
    color: '#0c1410',
    flexShrink: 0,
  },
  waiveCheckboxOn: {
    background: TEAL_LIGHT,
    borderColor: TEAL_LIGHT,
  },
  waiveSurchargeHint: {
    fontSize: '11px',
    color: '#7a8480',
    fontStyle: 'italic',
  },
  negativeTotalNote: {
    fontSize: '12px',
    color: '#E8799A',
    background: '#2a1419',
    border: '1px solid #5a2433',
    borderRadius: '8px',
    padding: '8px 12px',
    marginTop: '8px',
    lineHeight: 1.4,
  },
  totalValue: {
    fontSize: '18px',
    fontWeight: 700,
    color: GOLD,
  },
  saveBtn: {
    marginTop: '12px',
    background: TEAL_LIGHT,
    color: '#04342C',
    border: 'none',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  saveBtnDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },

  // Cooking list
  cookSubToggle: {
    display: 'flex',
    gap: '6px',
    marginBottom: '16px',
    background: '#1f2624',
    border: '1px solid #2d6a6a',
    borderRadius: '10px',
    padding: '4px',
  },
  cookSubBtn: {
    flex: 1,
    fontSize: '13px',
    fontWeight: 700,
    color: '#9aa5a0',
    background: 'transparent',
    border: 'none',
    borderRadius: '7px',
    padding: '9px',
    cursor: 'pointer',
  },
  cookSubBtnActive: {
    background: TEAL_MID,
    color: '#fff',
  },
  deliverCustDone: {
    color: '#5a8f6a',
    textDecoration: 'line-through',
  },
  // ── Dish Reference Card ───────────────────────────────────────────────────
  refCardPickerRow: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    marginBottom: '10px',
  },
  refCardSelect: {
    flex: 1,
    minWidth: 0,
    background: '#1f2624',
    border: '1px solid #2d6a6a',
    borderRadius: '8px',
    color: '#e8e2d4',
    fontSize: '14px',
    padding: '10px 12px',
  },
  refCardBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  refCardSection: {
    background: '#1a2320',
    border: '1px solid #2d3a36',
    borderRadius: '10px',
    padding: '12px 14px',
  },
  refCardSectionTitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: GOLD,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    marginBottom: '8px',
  },
  refCardRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    paddingBottom: '6px',
    borderBottom: '1px solid #2a3330',
    marginBottom: '6px',
    flexWrap: 'wrap',
  },
  refCardVariantLabel: {
    flex: 1,
    fontSize: '13px',
    color: '#e8e2d4',
    minWidth: '120px',
  },
  refCardPrice: {
    fontSize: '13px',
    fontWeight: 700,
    color: '#e8e2d4',
  },
  refCardCost: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  refCardMargin: {
    fontSize: '12px',
    fontWeight: 700,
    marginLeft: 'auto',
  },
  refCardIngRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '8px',
    paddingBottom: '4px',
    borderBottom: '1px solid #232a28',
    marginBottom: '4px',
  },
  refCardIngName: {
    fontSize: '13px',
    color: '#e8e2d4',
    flex: 1,
  },
  refCardIngStaple: {
    color: '#9aa5a0',
    fontStyle: 'italic',
  },
  refCardIngQty: {
    fontSize: '12px',
    color: '#9aa5a0',
    textAlign: 'right',
    whiteSpace: 'nowrap',
  },
  refCardExtrasLabel: {
    fontSize: '11px',
    color: TEAL_LIGHT,
    fontWeight: 600,
    marginBottom: '3px',
    marginTop: '2px',
  },
  refCardNotes: {
    width: '100%',
    background: '#1f2624',
    border: '1px solid #2d6a6a',
    borderRadius: '8px',
    color: '#e8e2d4',
    fontSize: '13px',
    padding: '10px 12px',
    minHeight: '100px',
    resize: 'vertical',
    lineHeight: 1.5,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  cookHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  cookSummary: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  resetBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#9aa5a0',
    background: 'transparent',
    border: '1px solid #37403c',
    borderRadius: '6px',
    padding: '5px 10px',
    cursor: 'pointer',
  },
  cookCategory: {
    marginBottom: '16px',
  },
  cookCategoryTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: TEAL_LIGHT,
    marginBottom: '6px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  cookItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    marginBottom: '6px',
    cursor: 'pointer',
    textAlign: 'left',
  },
  cookItemChecked: {
    opacity: 0.5,
  },
  checkbox: {
    width: '18px',
    height: '18px',
    borderRadius: '5px',
    border: '1.5px solid #5F5E5A',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    background: TEAL_LIGHT,
    borderColor: TEAL_LIGHT,
  },
  cookItemText: {
    flex: 1,
  },
  cookItemName: {
    fontSize: '14px',
    fontWeight: 600,
    color: CREAM,
  },
  cookItemVariant: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  cookItemQty: {
    fontSize: '14px',
    fontWeight: 700,
    color: GOLD,
  },

  // Shopping list
  genCard: {
    background: CARD,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '10px',
    padding: '14px',
    marginBottom: '14px',
  },
  genTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: '#fff',
    marginBottom: '4px',
  },
  genHint: {
    fontSize: '12px',
    color: '#9aa5a0',
    lineHeight: 1.5,
    marginBottom: '8px',
  },
  genToggleRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: CREAM,
    cursor: 'pointer',
  },
  genCheckbox: {
    width: '16px',
    height: '16px',
    accentColor: TEAL_LIGHT,
  },
  shopInputRow: {
    display: 'flex',
    gap: '8px',
    marginBottom: '14px',
    alignItems: 'flex-start',
  },
  shopAddBtn: {
    background: TEAL_LIGHT,
    color: '#04342C',
    border: 'none',
    borderRadius: '8px',
    width: '44px',
    height: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    flexShrink: 0,
  },
  shopItem: {
    display: 'flex',
    alignItems: 'center',
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '8px',
    marginBottom: '6px',
    overflow: 'hidden',
  },
  shopItemMain: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'transparent',
    border: 'none',
    padding: '11px 12px',
    cursor: 'pointer',
    textAlign: 'left',
  },
  shopItemText: {
    fontSize: '14px',
    color: CREAM,
  },
  shopItemTextChecked: {
    textDecoration: 'line-through',
    color: '#9aa5a0',
  },
  shopDeleteBtn: {
    background: 'transparent',
    border: 'none',
    color: '#5F5E5A',
    cursor: 'pointer',
    padding: '11px 12px',
    flexShrink: 0,
  },

  // Money tab
  moneyStatsBar: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    marginBottom: '8px',
  },
  moneyStatTile: {
    flex: '1 1 45%',
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '10px',
    padding: '10px 8px',
    textAlign: 'center',
  },
  moneyFootnote: {
    fontSize: '10px',
    color: '#7a8480',
    fontStyle: 'italic',
    marginBottom: '8px',
  },
  groupLabel: {
    fontSize: '12px',
    color: '#9aa5a0',
    fontWeight: 600,
  },
  moneyGroup: {
    marginBottom: '14px',
  },
  groupHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: '8px',
    padding: '4px 2px 6px',
    flexWrap: 'wrap',
  },
  groupTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: TEAL_LIGHT,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  groupTotals: {
    fontSize: '11px',
    color: '#9aa5a0',
  },
  moneyAmounts: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  moneyProfit: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#1D9E75',
  },
  sortRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    marginBottom: '12px',
    flexWrap: 'wrap',
  },
  sortBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    fontWeight: 600,
    color: '#9aa5a0',
    background: 'transparent',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '6px 10px',
    cursor: 'pointer',
  },
  sortBtnActive: {
    color: TEAL_LIGHT,
    borderColor: TEAL_LIGHT,
  },
  sortDirText: {
    fontSize: '11px',
  },
  moneyCount: {
    marginLeft: 'auto',
    fontSize: '12px',
    color: '#9aa5a0',
  },
  moneyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  moneyRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    gap: '10px',
  },
  moneyRowLeft: {
    minWidth: 0,
  },
  moneyName: {
    fontSize: '14px',
    fontWeight: 600,
    color: CREAM,
  },
  moneyMeta: {
    fontSize: '11px',
    color: '#9aa5a0',
    marginTop: '2px',
  },
  moneyRowRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexShrink: 0,
  },
  moneyAmount: {
    fontSize: '14px',
    fontWeight: 700,
    color: GOLD,
  },

  // Review banner (AI flags)

  // Per-item editor
  reviewItemCard: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '8px 10px',
    marginBottom: '6px',
  },
  reviewItemMain: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: 0,
  },
  itemExtraDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: TEAL_LIGHT,
    flexShrink: 0,
  },
  itemNotePreview: {
    fontSize: '11px',
    color: '#9aa5a0',
    fontStyle: 'italic',
    marginTop: '3px',
  },
  itemUpchargePreview: {
    fontSize: '11px',
    color: TEAL_LIGHT,
    marginTop: '3px',
  },
  itemUpchargeNeedsPrice: {
    fontSize: '11px',
    color: '#EF9F27',
    marginTop: '3px',
    fontWeight: 600,
  },
  itemEditor: {
    marginTop: '8px',
    paddingTop: '8px',
    borderTop: '1px dashed #37403c',
  },
  miniLabel: {
    fontSize: '11px',
    fontWeight: 600,
    color: '#9aa5a0',
    display: 'block',
    marginTop: '6px',
    marginBottom: '3px',
  },
  upchargeRow: {
    display: 'flex',
    gap: '6px',
  },
  itemEditorActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
    marginTop: '8px',
  },
  clearItemExtra: {
    background: 'transparent',
    color: '#993556',
    border: 'none',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  doneItemBtn: {
    background: TEAL_LIGHT,
    color: '#04342C',
    border: 'none',
    borderRadius: '6px',
    padding: '5px 14px',
    fontSize: '12px',
    fontWeight: 700,
    cursor: 'pointer',
  },

  // Custom charges
  customChargeList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '6px',
  },
  customChargeRow: {
    display: 'flex',
    gap: '6px',
    alignItems: 'center',
  },
  addChargeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    fontWeight: 600,
    color: TEAL_LIGHT,
    background: 'transparent',
    border: '1px dashed #2E6B6B',
    borderRadius: '8px',
    padding: '8px 12px',
    cursor: 'pointer',
    marginTop: '2px',
  },
  extraLine: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: '#cccccc',
    marginTop: '10px',
  },

  // Order card per-item sub-lines
  orderItemBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  orderItemSub: {
    fontSize: '11px',
    color: TEAL_LIGHT,
    paddingLeft: '2px',
  },
  orderItemNote: {
    fontSize: '11px',
    color: '#9aa5a0',
    fontStyle: 'italic',
    paddingLeft: '2px',
  },

  // Invoice
  invoiceOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.75)',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: '20px 12px',
    zIndex: 100,
    overflowY: 'auto',
  },
  invoiceScroll: {
    width: '100%',
    maxWidth: '380px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  invoiceCard: {
    width: '100%',
    background: 'linear-gradient(160deg, #14302e 0%, #1a1a1a 55%)',
    border: `1px solid ${GOLD}`,
    borderRadius: '16px',
    padding: '20px',
    boxSizing: 'border-box',
  },
  invoiceHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
  },
  invoiceLogo: {
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    background: '#085041',
    border: `2px solid ${TEAL_LIGHT}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: 700,
    color: TEAL_LIGHT,
    flexShrink: 0,
  },
  invoiceBrand: {
    fontSize: '15px',
    fontWeight: 700,
    color: '#fff',
  },
  invoiceTagline: {
    fontSize: '11px',
    color: TEAL_LIGHT,
    fontStyle: 'italic',
  },
  invoiceMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '8px',
  },
  invoiceCustomer: {
    fontSize: '17px',
    fontWeight: 700,
    color: CREAM,
  },
  invoiceDate: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  invoiceDivider: {
    height: '1px',
    background: '#37403c',
    margin: '12px 0',
  },
  invoiceItems: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  invoiceItemBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
  },
  invoiceItemLine: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '10px',
  },
  invoiceItemName: {
    fontSize: '14px',
    fontWeight: 600,
    color: CREAM,
  },
  invoiceItemPrice: {
    fontSize: '14px',
    fontWeight: 700,
    color: CREAM,
    flexShrink: 0,
  },
  invoiceItemVariant: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  invoiceItemExtra: {
    fontSize: '11px',
    color: TEAL_LIGHT,
  },
  invoiceItemNote: {
    fontSize: '11px',
    color: '#b8a06a',
    fontStyle: 'italic',
  },
  invoiceTotals: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  invoiceTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '13px',
    color: '#cccccc',
  },
  invoiceGrandTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '12px',
    paddingTop: '12px',
    borderTop: `1px solid ${GOLD}`,
  },
  invoiceGrandValue: {
    fontSize: '22px',
    fontWeight: 700,
    color: GOLD,
  },
  invoiceNotes: {
    fontSize: '12px',
    color: '#9aa5a0',
    fontStyle: 'italic',
    marginTop: '12px',
    paddingTop: '10px',
    borderTop: '1px dashed #37403c',
  },
  invoiceFooter: {
    fontSize: '11px',
    color: TEAL_LIGHT,
    textAlign: 'center',
    marginTop: '14px',
  },
  invoiceClose: {
    marginTop: '16px',
    background: TEAL_LIGHT,
    color: '#04342C',
    border: 'none',
    borderRadius: '10px',
    padding: '12px 40px',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  invoiceShareBtn: {
    marginTop: '16px',
    background: '#c9a84c',
    color: '#1a3a3a',
    border: 'none',
    borderRadius: '10px',
    padding: '12px 40px',
    fontSize: '14px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  // ── Invoice weight warnings ────────────────────────────────────────────────
  invoiceNotFinalBanner: {
    background: '#EF9F27',
    color: '#1a1a1a',
    fontWeight: 800,
    fontSize: '12px',
    textAlign: 'center',
    padding: '8px 10px',
    borderRadius: '8px',
    margin: '10px 0 4px',
    letterSpacing: '0.3px',
    lineHeight: 1.3,
  },
  invoiceItemPending: {
    fontSize: '11px',
    color: '#EF9F27',
    fontStyle: 'italic',
    marginTop: '1px',
  },
  invoiceTotalPendingNote: {
    fontSize: '11px',
    color: '#EF9F27',
    fontStyle: 'italic',
    textAlign: 'right',
    marginTop: '4px',
    lineHeight: 1.3,
  },
  invoiceHint: {
    fontSize: '12px',
    color: '#9aa5a0',
    marginTop: '8px',
    textAlign: 'center',
  },
  // ── Reheat instructions card ───────────────────────────────────────────────
  reheatSubhead: {
    fontSize: '11px',
    color: GOLD,
    fontWeight: 600,
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
  },
  reheatBlocks: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  reheatBlock: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  reheatDishes: {
    fontSize: '14px',
    fontWeight: 700,
    color: CREAM,
  },
  reheatBody: {
    fontSize: '13px',
    color: '#cfd6d2',
    lineHeight: 1.45,
  },

  // Review open button (replaces passive banner)
  reviewOpenBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    width: '100%',
    background: '#3a2e08',
    border: '1px solid #C49A3C',
    borderRadius: '10px',
    padding: '12px 14px',
    cursor: 'pointer',
    marginBottom: '10px',
    color: GOLD,
    textAlign: 'left',
  },
  reviewOpenText: { flex: 1 },
  reviewOpenTitle: { fontSize: '13px', fontWeight: 700, color: GOLD },
  reviewOpenSub: { fontSize: '11px', color: '#cbb87a', marginTop: '1px' },

  // Review modal
  reviewModalCard: {
    width: '100%',
    maxWidth: '420px',
    background: CARD,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '14px',
    padding: '18px',
    boxSizing: 'border-box',
  },
  reviewModalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  reviewModalTitle: { fontSize: '17px', fontWeight: 700, color: '#fff' },
  reviewProgress: { fontSize: '12px', color: '#9aa5a0', marginBottom: '14px' },
  reviewStep: { display: 'flex', flexDirection: 'column' },
  reviewReasonBox: {
    background: '#1a1a1a',
    border: '1px solid #C49A3C',
    borderRadius: '8px',
    padding: '12px',
    fontSize: '14px',
    color: CREAM,
    lineHeight: 1.4,
  },
  reviewItemContext: {
    fontSize: '12px',
    color: '#9aa5a0',
    marginTop: '8px',
  },
  reviewField: {
    display: 'flex',
    flexDirection: 'column',
    marginTop: '12px',
  },
  reviewActionBtn: {
    marginTop: '8px',
    alignSelf: 'flex-start',
    background: TEAL_LIGHT,
    color: '#04342C',
    border: 'none',
    borderRadius: '8px',
    padding: '8px 16px',
    fontSize: '13px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  reviewOr: {
    fontSize: '11px',
    color: '#7a8480',
    textAlign: 'center',
    margin: '10px 0 4px',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  reviewSkipBtn: {
    marginTop: '14px',
    background: 'transparent',
    color: '#9aa5a0',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '9px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  reviewNav: {
    display: 'flex',
    justifyContent: 'center',
    gap: '6px',
    marginTop: '14px',
  },
  reviewDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    border: 'none',
    background: '#37403c',
    cursor: 'pointer',
    padding: 0,
  },
  reviewDotActive: { background: TEAL_LIGHT },
  reviewDotDone: { background: '#1D9E75' },
  reviewDone: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    padding: '24px 0 8px',
    textAlign: 'center',
  },
  reviewDoneText: { fontSize: '14px', color: CREAM, fontWeight: 600 },

  // Sous vide reprice button
  sousVideBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    marginTop: '12px',
    background: '#0f2e2a',
    color: TEAL_LIGHT,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '8px',
    padding: '11px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  weightPriceHint: {
    fontSize: '12px',
    color: TEAL_LIGHT,
    marginTop: '4px',
    fontWeight: 600,
  },

  // Pending weight state on order cards
  pendingPrice: {
    fontSize: '12px',
    color: '#EF9F27',
    fontStyle: 'italic',
    fontWeight: 600,
  },
  setWeightBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    marginTop: '5px',
    background: '#0f2e2a',
    color: TEAL_LIGHT,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '6px',
    padding: '5px 10px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  updateAllWeightsBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    marginBottom: '10px',
    background: '#0f2e2a',
    color: TEAL_LIGHT,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '8px',
    padding: '11px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
  },

  // Weight + photo modal
  weightModalCard: {
    width: '100%',
    maxWidth: '400px',
    background: CARD,
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '14px',
    padding: '18px',
    boxSizing: 'border-box',
    maxHeight: '88vh',
    overflowY: 'auto',
  },
  weightStepLabel: {
    fontSize: '11px',
    color: TEAL_LIGHT,
    marginTop: '2px',
  },
  amendBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '7px',
    flex: '1 1 100%',
    background: '#2a2333',
    color: '#b89adb',
    border: '1px solid #6b51a0',
    borderRadius: '10px',
    padding: '13px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  amendOrderPicker: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '4px',
  },
  amendOrderChip: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
  },
  amendOrderChipActive: {
    borderColor: TEAL_LIGHT,
    background: '#0f2e2a',
  },
  amendChipName: {
    fontSize: '14px',
    fontWeight: 600,
    color: CREAM,
  },
  amendChipMeta: {
    fontSize: '12px',
    color: '#9aa5a0',
    flexShrink: 0,
  },
  amendCurrentBox: {
    background: '#14302e',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '8px',
    padding: '10px 12px',
    margin: '4px 0 4px',
  },
  amendCurrentTitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: TEAL_LIGHT,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '6px',
  },
  amendCurrentItem: {
    fontSize: '13px',
    color: CREAM,
    padding: '2px 0',
  },
  weightDeferNote: {
    fontSize: '12px',
    color: '#9aa5a0',
    background: '#0f2e2a',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '8px',
    padding: '10px 12px',
    margin: '10px 0 0',
    lineHeight: 1.4,
  },
  weightIntentNote: {
    fontSize: '12px',
    color: '#9aa5a0',
    fontStyle: 'italic',
    background: '#1a1a1a',
    borderRadius: '6px',
    padding: '8px 10px',
    margin: '4px 0 12px',
  },
  weightModalHint: {
    fontSize: '11px',
    color: '#7a8480',
    marginTop: '8px',
    lineHeight: 1.4,
  },
  photoUploadBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    width: '100%',
    background: '#1a1a1a',
    color: TEAL_LIGHT,
    border: '1px dashed #2E6B6B',
    borderRadius: '8px',
    padding: '14px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    boxSizing: 'border-box',
  },
  photoPreviewWrap: {
    position: 'relative',
    borderRadius: '8px',
    overflow: 'hidden',
    border: '1px solid #37403c',
  },
  photoPreview: {
    width: '100%',
    display: 'block',
    maxHeight: '260px',
    objectFit: 'contain',
    background: '#000',
  },
  photoRemoveBtn: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    background: 'rgba(0,0,0,0.7)',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    padding: '5px 9px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
  },

  // Storage gauge in Money tab
  storageGauge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '12px',
    color: '#9aa5a0',
    padding: '12px 14px',
    marginTop: '8px',
    background: CARD,
    borderRadius: '8px',
    flexWrap: 'wrap',
  },
  storageGaugeNote: {
    fontSize: '11px',
    color: '#7a8480',
    marginLeft: 'auto',
  },

  // Order photos in Money tab
  moneyRowWrap: {
    display: 'flex',
    flexDirection: 'column',
  },
  orderPhotosWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '10px 4px 4px',
  },
  orderPhotoItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  orderPhotoLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: TEAL_LIGHT,
  },
  orderPhotoLoading: {
    fontSize: '11px',
    color: '#7a8480',
    fontStyle: 'italic',
  },
  orderPhotoImg: {
    width: '100%',
    borderRadius: '8px',
    border: '1px solid #37403c',
    maxHeight: '320px',
    objectFit: 'contain',
    background: '#000',
  },

  // Cook tab revenue bar
  cookRevenueBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#0f2e2a',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '10px',
    padding: '12px 14px',
    marginBottom: '12px',
  },
  cookRevenueLabel: {
    fontSize: '13px',
    color: '#9aa5a0',
  },
  cookRevenueValue: {
    fontSize: '18px',
    fontWeight: 700,
    color: TEAL_LIGHT,
  },

  // Shop tab cost bar
  shopCostBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '10px',
    padding: '11px 14px',
    marginBottom: '12px',
  },
  shopCostLabel: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  shopCostValue: {
    fontSize: '16px',
    fontWeight: 700,
    color: GOLD,
  },
  // ── Dish picker ────────────────────────────────────────────────────────────
  dishPickerGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '7px',
    marginTop: '8px',
  },
  dishPickerChip: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '7px 10px',
    fontSize: '12px',
    color: '#9aa5a0',
    cursor: 'pointer',
    textAlign: 'left',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  dishPickerChipWeek: {
    border: '1px solid #2d6a6a',
    color: '#d8d2c4',
    background: '#1a2e2e',
  },
  dishPickerChipSelected: {
    background: '#c9a84c',
    color: '#1a3a3a',
    border: '1px solid #c9a84c',
    fontWeight: 700,
  },
  dishPickerDot: {
    color: '#3fb8a0',
    fontSize: '8px',
  },
  dishPickerControls: {
    marginTop: '12px',
    paddingTop: '12px',
    borderTop: '1px solid #2d3a36',
  },
  dishPickerVariants: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginTop: '6px',
    marginBottom: '10px',
  },
  dishPickerVariantBtn: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '9px 12px',
    fontSize: '13px',
    color: '#9aa5a0',
    cursor: 'pointer',
    textAlign: 'left',
  },
  dishPickerVariantBtnOn: {
    background: '#1a3a3a',
    border: '1px solid #2d6a6a',
    color: '#e8e2d4',
    fontWeight: 600,
  },
  dishPickerServing: {
    color: '#7abf7a',
    fontSize: '11px',
    fontWeight: 400,
  },
  dishPickerCountRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  dishPickerCounter: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },

  // Money tab search row
  moneySearchRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
  },
  moneySearchInput: {
    flex: 1,
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
    fontSize: '14px',
    color: CREAM,
    outline: 'none',
  },
  moneySearchClear: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    background: 'transparent',
    border: '1px solid #37403c',
    borderRadius: '8px',
    color: '#9aa5a0',
    cursor: 'pointer',
    flexShrink: 0,
  },
  chartToggleBtn: {
    background: 'transparent',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '8px',
    padding: '8px 14px',
    fontSize: '13px',
    fontWeight: 600,
    color: TEAL_LIGHT,
    cursor: 'pointer',
    flexShrink: 0,
  },
  chartToggleBtnActive: {
    background: '#0f2e2a',
    borderColor: TEAL_LIGHT,
  },

  // Rich per-group summary header
  groupHeaderRich: {
    background: '#14302e',
    border: `1px solid ${TEAL_MID}`,
    borderRadius: '10px',
    padding: '12px 14px',
    marginBottom: '8px',
  },
  groupHeaderTop: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  groupOrderCount: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  groupStatsRow: {
    display: 'flex',
    gap: '8px',
  },
  groupStat: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  groupStatValue: {
    fontSize: '15px',
    fontWeight: 700,
    color: CREAM,
  },
  groupStatLabel: {
    fontSize: '10px',
    color: '#7a8480',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },

  // Profit chart
  chartCard: {
    background: CARD,
    border: '1px solid #37403c',
    borderRadius: '12px',
    padding: '14px',
    marginBottom: '14px',
  },
  chartHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  chartTitle: {
    fontSize: '14px',
    fontWeight: 700,
    color: CREAM,
  },
  chartSubtitle: {
    fontSize: '12px',
    color: '#9aa5a0',
  },
  chartSvg: {
    width: '100%',
    height: 'auto',
    display: 'block',
  },
  chartLegend: {
    fontSize: '11px',
    color: '#7a8480',
    marginTop: '8px',
    lineHeight: 1.4,
  },

  // CSV import
  csvBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '7px',
    flex: '1 1 100%',
    background: '#1f2937',
    color: '#93b4d4',
    border: '1px solid #3d5a7a',
    borderRadius: '10px',
    padding: '13px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  checkFormBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '7px',
    flex: '1 1 100%',
    background: '#1a2e1a',
    color: '#7abf7a',
    border: '1px solid #3a6a3a',
    borderRadius: '10px',
    padding: '13px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  spinning: {
    animation: 'spin 1s linear infinite',
  },
  csvProgress: {
    fontSize: '13px',
    color: TEAL_LIGHT,
    textAlign: 'center',
    padding: '8px 0',
  },
  csvResultsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    marginBottom: '12px',
    maxHeight: '320px',
    overflowY: 'auto',
  },
  csvResultRow: {
    background: '#1a1a1a',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px 12px',
  },
  csvResultName: {
    fontSize: '14px',
    fontWeight: 600,
    color: CREAM,
    marginBottom: '3px',
  },
  csvResultItems: {
    fontSize: '12px',
    color: '#9aa5a0',
    lineHeight: 1.4,
  },
  csvResultItem: {
    marginRight: '4px',
  },
  csvResultFlag: {
    color: '#EF9F27',
  },
  csvResultError: {
    fontSize: '12px',
    color: '#E8799A',
    fontStyle: 'italic',
  },
  csvBackBtn: {
    width: '100%',
    background: 'transparent',
    color: '#9aa5a0',
    border: '1px solid #37403c',
    borderRadius: '8px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    marginTop: '8px',
  },
};
